services:
  php81:
    build:
      context: ./php-fpm/81
    container_name: ${PHP81_CONTAINER}
    volumes:
      - ${PROJECTS_PATH}:/var/www
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - appNet
    command: sh -c "crond && php-fpm"

  php82:
    build:
      context: ./php-fpm/82
    container_name: ${PHP82_CONTAINER}
    volumes:
      - ${PROJECTS_PATH}:/var/www
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - appNet

  php84:
    build:
      context: ./php-fpm/84
    container_name: ${PHP84_CONTAINER}
    volumes:
      - ${PROJECTS_PATH}:/var/www
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - appNet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ${PROJECTS_PATH}:/var/www
    depends_on:
      - php81
      - php82
      - php84
    networks:
      appNet:
        aliases:
          - sample.localhost

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - appNet

  redis-webui:
    image: erikdubbelboer/phpredisadmin:latest
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
      - REDIS_1_AUTH=${REDIS_PASSWORD}
    ports:
      - "${REDIS_WEBUI_PORT}:80"
    depends_on:
      - redis
    networks:
      - appNet

  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - appNet

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - appNet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appNet

  buggregator:
    image: butschster/buggregator:latest
    ports:
      - 8000:8000
      - 1025:1025
      - 9912:9912
      - 9913:9913
    environment:
      AUTH_ENABLED: false
      AUTH_USERNAME: admin
      AUTH_PASSWORD: secret
    networks:
      - appNet

volumes:
  mysql_data:
  pg_data:

networks:
  appNet:
    driver: ${NETWORKS_DRIVER}
